### ISSUE TITLE
Error encountered when executing nwbetter

### ISSUE THREAD

**Issue by Cearul** [defmulti/nwbetter#2]
I believe I have installed this userscript successfully, however, I encounter this issue when executing nwbetter with a permalink to a torrent. Not sure how else to troubleshoot. Any help would be greatly appreciated!

```
Logging in to notwhat ...
Traceback (most recent call last):
  File "./nwbetter", line 231, in <module>
    main()
  File "./nwbetter", line 116, in main
    api = nwapi.NwAPI(username, password)
  File "/media/sdu/genuflect/nwbetter/nwapi.py", line 82, in __init__
    self._login()
  File "/media/sdu/genuflect/nwbetter/nwapi.py", line 92, in _login
    accountinfo = self.request('index')
  File "/media/sdu/genuflect/nwbetter/nwapi.py", line 119, in request
    raise RequestException
nwapi.RequestException
```

**Comment by Cearul** [comment]
So after installing Python 3.5.3, I no longer receive the error above.

However, I now receive this error:
`  File "nwbetter", line 85
    print 'Please edit the configuration file: %s' % args.config
                                                 ^
SyntaxError: Missing parentheses in call to 'print'`
